### ISSUE TITLE
error detected in the compilation of "kernel.cu"

### ISSUE THREAD

**Issue by hung-th** [koszullab/instaGRAAL#18]
After overcoming the #17 issue, the pyramid files were generated successfully but then failed at a nvcc compilation step.

After this:
```
2020-11-22 22:08:36,640 :: INFO :: loading kernels ...
2020-11-22 22:08:36,642 :: INFO :: size array in shared memory = 1536
```
(Full log here: [instagraal.log](https://github.com/koszullab/instaGRAAL/files/5582884/instagraal.log))

Error returns:
```
Traceback (most recent call last):
  File "/usr/local/bin/instagraal", line 11, in <module>
    load_entry_point('instagraal==0.1.6', 'console_scripts', 'instagraal')()
  File "/usr/local/lib/python3.7/dist-packages/instagraal-0.1.6-py3.7.egg/instagraal/instagraal.py", line 1178, in main
    output_folder=output_folder,
  File "/usr/local/lib/python3.7/dist-packages/instagraal-0.1.6-py3.7.egg/instagraal/instagraal.py", line 160, in __init__
    output_folder=output_folder,
  File "/usr/local/lib/python3.7/dist-packages/instagraal-0.1.6-py3.7.egg/instagraal/simu_single.py", line 168, in __init__
    self.pos,
  File "/usr/local/lib/python3.7/dist-packages/instagraal-0.1.6-py3.7.egg/instagraal/cuda_lib_gl_single.py", line 294, in __init__
    self.loadProgram(kernel_adapt_entry_point)
  File "/usr/local/lib/python3.7/dist-packages/instagraal-0.1.6-py3.7.egg/instagraal/cuda_lib_gl_single.py", line 1979, in loadProgram
    options=[
  File "/usr/local/lib/python3.7/dist-packages/pycuda-2020.1-py3.7-linux-x86_64.egg/pycuda/compiler.py", line 358, in __init__
    include_dirs,
  File "/usr/local/lib/python3.7/dist-packages/pycuda-2020.1-py3.7-linux-x86_64.egg/pycuda/compiler.py", line 298, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/usr/local/lib/python3.7/dist-packages/pycuda-2020.1-py3.7-linux-x86_64.egg/pycuda/compiler.py", line 155, in compile_plain
    stderr=stderr.decode("utf-8", "replace"),
pycuda.driver.CompileError: nvcc compilation of /tmp/tmp7tvm61k6/kernel.cu failed
[command: nvcc --cubin -arch sm_75 -I/usr/local/lib/python3.7/dist-packages/pycuda-2020.1-py3.7-linux-x86_64.egg/pycuda/cuda kernel.cu]
[stderr:
kernel.cu(432): warning: variable "selec_smem" was set but never used

kernel.cu(437): warning: variable "local_count" was set but never used

kernel.cu(505): warning: variable "pos_fa_down" was declared but never referenced

kernel.cu(521): warning: variable "id_alter_contig" was declared but never referenced

kernel.cu(521): warning: variable "condition_3" was declared but never referenced

kernel.cu(521): warning: variable "condition_4" was declared but never referenced

kernel.cu(740): warning: variable "sub_pos_f_pop" was set but never used

kernel.cu(744): warning: variable "sub_l_cont_f_pop" was set but never used

kernel.cu(746): warning: variable "l_cont_bp_f_pop" was set but never used

kernel.cu(751): warning: variable "start_bp_f_pop" was set but never used

kernel.cu(754): warning: variable "or_f_pop" was set but never used

kernel.cu(1083): warning: variable "contig_f_pop" was set but never used

kernel.cu(1084): warning: variable "pos_f_pop" was set but never used

kernel.cu(1085): warning: variable "sub_pos_f_pop" was set but never used

kernel.cu(1086): warning: variable "l_cont_f_pop" was set but never used

kernel.cu(1087): warning: variable "sub_l_cont_f_pop" was set but never used

kernel.cu(1088): warning: variable "l_cont_bp_f_pop" was set but never used

kernel.cu(1091): warning: variable "start_bp_f_pop" was set but never used

kernel.cu(1092): warning: variable "id_prev_f_pop" was set but never used

kernel.cu(1093): warning: variable "id_next_f_pop" was set but never used

kernel.cu(1375): warning: variable "contig_f_pop" was set but never used

kernel.cu(1376): warning: variable "pos_f_pop" was set but never used

kernel.cu(1377): warning: variable "sub_pos_f_pop" was set but never used

kernel.cu(1378): warning: variable "l_cont_f_pop" was set but never used

kernel.cu(1379): warning: variable "l_cont_bp_f_pop" was set but never used

kernel.cu(1380): warning: variable "sub_l_cont_f_pop" was set but never used

kernel.cu(1383): warning: variable "start_bp_f_pop" was set but never used

kernel.cu(1384): warning: variable "id_prev_f_pop" was set but never used

kernel.cu(1385): warning: variable "id_next_f_pop" was set but never used

kernel.cu(1690): warning: variable "contig_f_pop" was set but never used

kernel.cu(1691): warning: variable "pos_f_pop" was set but never used

kernel.cu(1692): warning: variable "sub_pos_f_pop" was set but never used

kernel.cu(1693): warning: variable "l_cont_f_pop" was set but never used

kernel.cu(1694): warning: variable "l_cont_bp_f_pop" was set but never used

kernel.cu(1695): warning: variable "sub_l_cont_f_pop" was set but never used

kernel.cu(1698): warning: variable "start_bp_f_pop" was set but never used

kernel.cu(1699): warning: variable "id_prev_f_pop" was set but never used

kernel.cu(1700): warning: variable "id_next_f_pop" was set but never used

kernel.cu(1713): warning: variable "id_prev_f_ins" was set but never used

kernel.cu(2141): warning: variable "pop_is_ext" was set but never used

kernel.cu(2421): warning: variable "or_f_cut_a" was set but never used

kernel.cu(2431): warning: variable "or_f_cut_b" was set but never used

kernel.cu(2749): warning: variable "id_prev_f_ins" was set but never used

kernel.cu(2991): warning: variable "or_f_cut" was set but never used

kernel.cu(3369): warning: variable "sub_pos_fA" was set but never used

kernel.cu(3373): warning: variable "len_bp_fA" was set but never used

kernel.cu(3374): warning: variable "sub_len_fA" was set but never used

kernel.cu(3375): warning: variable "start_bp_fA" was set but never used

kernel.cu(3376): warning: variable "id_prev_fA" was set but never used

kernel.cu(3377): warning: variable "id_next_fA" was set but never used

kernel.cu(3378): warning: variable "circ_fA" was set but never used

kernel.cu(3379): warning: variable "or_fA" was set but never used

kernel.cu(3384): warning: variable "sub_pos_fB" was set but never used

kernel.cu(3388): warning: variable "len_bp_fB" was set but never used

kernel.cu(3389): warning: variable "sub_len_fB" was set but never used

kernel.cu(3390): warning: variable "start_bp_fB" was set but never used

kernel.cu(3391): warning: variable "id_prev_fB" was set but never used

kernel.cu(3392): warning: variable "id_next_fB" was set but never used

kernel.cu(3393): warning: variable "circ_fB" was set but never used

kernel.cu(3394): warning: variable "or_fB" was set but never used

kernel.cu(3712): warning: variable "is_activ_fi" was set but never used

kernel.cu(3712): warning: variable "is_rep_fi" was set but never used

kernel.cu(3712): warning: variable "swap" was declared but never referenced

kernel.cu(3714): warning: variable "s" was declared but never referenced

kernel.cu(3716): warning: variable "is_circle" was set but never used

kernel.cu(3775): warning: variable "is_activ_fi" was set but never used

kernel.cu(3775): warning: variable "is_rep_fi" was set but never used

kernel.cu(3775): warning: variable "swap" was declared but never referenced

kernel.cu(3777): warning: variable "s" was declared but never referenced

kernel.cu(3823): error: identifier "__shfl_down" is undefined

kernel.cu(3936): warning: variable "tmp_val" was declared but never referenced

kernel.cu(4010): warning: variable "id" was declared but never referenced

kernel.cu(4056): warning: variable "start" was declared but never referenced

kernel.cu(4398): warning: variable "row" was declared but never referenced

kernel.cu(4398): warning: variable "col" was declared but never referenced

kernel.cu(4399): warning: variable "is_circle" was declared but never referenced

kernel.cu(4636): warning: variable "max_len" was set but never used

kernel.cu(4644): warning: variable "min_id_c_new" was declared but never referenced

kernel.cu(4876): warning: variable "condition_pix" was set but never used

kernel.cu(4877): warning: variable "start" was declared but never referenced

1 error detected in the compilation of "kernel.cu".
]
```

I compiled the `linux-source-4.19` for kernel and `CUDA-11.1`. I tried reinstalling everything but didn't seem to troubleshoot the problem.

Thank you very much for your help.

**Comment by FirePanda007** [comment]
Here you can see the error:
```
kernel.cu(3823): error: identifier "__shfl_down" is undefined
```
__shfl_down() is deprecated and deleted from high version device ( link ) so needs to be changed to __shfl_down_sync().


Edit  line 4-12 of instagraal/kernels/kernel_sparse_adapt.cu

 ```
 #if !defined(__CUDA_ARCH__) || __CUDA_ARCH__ >= 300
__device__ inline double __shfl_down(double var, unsigned int srcLane, int width=32) {
    int2 a = *reinterpret_cast<int2*>(&var);
    a.x = __shfl_down_sync(a.x, srcLane, width);
    a.y = __shfl_down_sync(a.y, srcLane, width);
    return *reinterpret_cast<double*>(&a);
}
 #else
__device__ inline double __shfl_down(double var, unsigned int srcLane, int width=32) {
    int2 a = *reinterpret_cast<int2*>(&var);
    a.x = __shfl_down(a.x, srcLane, width);
    a.y = __shfl_down(a.y, srcLane, width);
    return *reinterpret_cast<double*>(&a);
}
 #endif
```


Do the same for instagraal/kernels/kernel_sparse.cu.

It seems that you can edit these files before install instaGRAAL, or directly revise the files in Python-XX/site-packages/instagraal. Either is OK.

After the above operation, some warnings still exist(may be deprecated in the future), but the program can run successfully。

I hope it helps you.

**Comment by hung-th** [comment]
Thank you so much @FirePanda007 for your help.

The kernel was successfully compiled and instagraal ran the cycles.

However, after 99 cycles, when it is generating new fasta file. The following error occured.
```
2020-12-03 23:04:42,690 :: INFO :: generate new fasta file...
2020-12-03 23:07:10,921 :: INFO :: cycle = 97
2020-12-04 00:46:42,920 :: INFO :: generate new fasta file...
2020-12-04 00:49:11,074 :: INFO :: cycle = 98
2020-12-04 02:28:41,679 :: INFO :: generate new fasta file...
2020-12-04 02:31:09,097 :: INFO :: cycle = 99
2020-12-04 04:10:34,708 :: INFO :: generate new fasta file...
INFO :: generate new fasta file...                                                         
Traceback (most recent call last):                                                         
  File "/usr/local/bin/instagraal", line 11, in <module>                                   
    load_entry_point('instagraal==0.1.6', 'console_scripts', 'instagraal')()               
  File "/usr/local/lib/python3.7/dist-packages/instagraal-0.1.6-py3.7.egg/instagraal/instag|
raal.py", line 1201, in main                                                               
    p2.ctx_gl.pop()                                                                        
AttributeError: 'instagraal_class' object has no attribute 'ctx_gl'
```

Do you have any idea what caused this error? And since it has already ran through 99 cycles, is it safe to use the fasta file generated?

Thanks a lot for your help.

**Comment by nadegeguiglielmoni** [comment]
Yes, sorry, this is a glitch remaining that happens at the end of an instaGRAAL run, but the fasta file is good to use. The program ran for 100 cycles, as it starts from 0. You should now polish genome.fasta with instagraal-polish.

**Comment by hung-th** [comment]
Sorry for having more problems, but instagraal-polish throws another error:

```
File "/usr/local/lib/python3.7/dist-packages/instagraal-0.1.6-py3.7.egg/instagraal/parse_info_frags.py", line 22, in <module>
    from Bio.Seq import Seq, IUPAC
ImportError: cannot import name 'IUPAC' from 'Bio.Seq' (/usr/local/lib/python3.7/dist-packages/Bio/Seq.py)
```

I installed `biopython-1.78` during the installation pipeline of instaGRAAL. And I checked the document and also the Seq.py and I couldn't find a module called IUPAC. I wondered if it is now the Bio.Data.IUPACData module?

Which version of biopython is recommended?

**Comment by nadegeguiglielmoni** [comment]
It seems that IUPAC has been dropped in the latest version (1.78) and was still there up to 1.75.

**Comment by hung-th** [comment]
Thanks I downgraded the biopython to 1.75 and it worked, but here is another error:

Command:
`sudo instagraal-polish -m polishing -i info_frags.txt -f genome.fasta -o genome_polished.fasta`

Output:
```
Appending the rest...
Traceback (most recent call last):
  File "/usr/local/bin/instagraal-polish", line 11, in <module>
    load_entry_point('instagraal==0.1.6', 'console_scripts', 'instagraal-polish')()
  File "/usr/local/lib/python3.7/dist-packages/instagraal-0.1.6-py3.7.egg/instagraal/parse_info_frags.py", line 949, in main
    output=output_file,
  File "/usr/local/lib/python3.7/dist-packages/instagraal-0.1.6-py3.7.egg/instagraal/parse_info_frags.py", line 645, in write_fasta
    seq_to_add = init_genome[init_contig][start:end]
KeyError: '000024F'
```

**Comment by nadegeguiglielmoni** [comment]
The -f file should not be genome.fasta but instead the original assembly file.

**Comment by hung-th** [comment]
Thank you all so much, I successfully ran the entire instaGRAAL and polish pipeline. The output genome is perfect at chromosome-scale.

```
sum = 621009970, n = 512, ave = 1212910.10, largest = 85637745
N50 = 59971594, n = 5
N60 = 57281449, n = 6
N70 = 57082107, n = 7
N80 = 55121989, n = 8
N90 = 49653693, n = 9
N100 = 65, n = 512
N_count = 0
Gaps = 0
```
