### ISSUE TITLE
Pyramid building issues with local version

### ISSUE THREAD

**Issue by JamieAlfieri** [koszullab/instaGRAAL#23]
Hello,

When I try to run instaGRAAL locally, I get an error that the first pyramid file does not exist.
Here are my specs:
OS: Ubuntu 18.04
Cuda: Cuda 10.2
Driver: 440.33.11
OpenGL libraries, HDF5 serialization library, and boost libraries are all up to date.
Pycuda was successfully installed.
I've deleted pyramids folder every time I've re-run the command.

The specific error message:

```
INFO :: Selected_device: GeForce RTX 2080 Ti
Traceback (most recent call last):
  File "/usr/local/bin/instagraal", line 11, in <module>
    load_entry_point('instagraal', 'console_scripts', 'instagraal')()
  File "/home/blackmonlab/Desktop/instafolder/spb_hic/src/instagraal/instagraal/instagraal.py", line 2164, in main
    output_folder=output_folder,
  File "/home/blackmonlab/Desktop/instafolder/spb_hic/src/instagraal/instagraal/instagraal.py", line 223, in __init__
    output_folder=output_folder,
  File "/home/blackmonlab/Desktop/instafolder/spb_hic/src/instagraal/instagraal/simu_single.py", line 76, in __init__
    self.select_data_set(name)
  File "/home/blackmonlab/Desktop/instafolder/spb_hic/src/instagraal/instagraal/simu_single.py", line 747, in select_data_set
    thresh_factor=self.thresh_factor,
  File "/home/blackmonlab/Desktop/instafolder/spb_hic/src/instagraal/instagraal/pyramid_sparse.py", line 64, in build_and_filter
    build(base_folder, init_size_pyramid, factor, min_bin_per_contig)
  File "/home/blackmonlab/Desktop/instafolder/spb_hic/src/instagraal/instagraal/pyramid_sparse.py", line 242, in build
    pyramid_handle = h5py.File(hdf5_pyramid_file)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'spb_hic/pyramids/pyramid_1_no_thresh/pyramid.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
Aborted ng(core dumped)
``ect_data_set(name)
  File "/home/blackmonlab/Desktop/instafolder/spb_hic/src/instagraal/instagraal/simu_single.py", line 747, in select_data_set
    thresh_factor=self.thresh_factor,
  File "/home/blackmonlab/Desktop/instafolder/spb_hic/src/instagraal/instagraal/pyramid_sparse.py", line 64, in build_and_filter
    build(base_folder, init_size_pyramid, factor, min_bin_per_contig)
  File "/home/blackmonlab/Desktop/instafolder/spb_hic/src/instagraal/instagraal/pyramid_sparse.py", line 242, in build
    pyramid_handle = h5py.File(hdf5_pyramid_file)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'spb_hic/pyramids/pyramid_1_no_thresh/pyramid.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
Aborted ng(core dumped)
```

My instagraal.log file is only two lines:
```
2021-04-15 12:51:06,736 :: INFO :: Selected_device: GeForce RTX 2080 Ti
2021-04-15 12:51:09,460 :: INFO :: start filtering
```

Does anyone have any suggestions for fixing this? I've tried to run the docker version instead, but I get a different error (FileNotFoundError: [Errno 2] No such file or directory: 'spb_hic/pyramids') from that.

**Comment by JamieAlfieri** [comment]
My error: I did not see that this issue was resolved [here](https://github.com/koszullab/instaGRAAL/issues/17#issue-734035714) . I needed to roll back my hdf5 library.
