### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by gorliver** [koszullab/instaGRAAL#30]
Hi,
I have used the docker image through singualrity on a HPC GPU node but I got the following issue:
The command is:
singularity run -B $PWD:/data --nv -C instagraal_latest.sif instagraal /data/hicstuff_out /data/assembly.pilon.fasta /data/instagraal_out

and here is the message:
INFO :: start filtering
INFO :: nfrags = 13398071
INFO :: n init frags = 13398071
INFO :: mean sparsity = 7.225973490676552e-07
INFO :: median sparsity = 3.731880440227542e-07
INFO :: std sparsity = 1.2747863138429238e-06
INFO :: max_sparsity = 0.0006414356175810099
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_pdf.py", line 2593, in print_pdf
    self.figure.draw(renderer)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py", line 1864, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/collections.py", line 931, in draw
    Collection.draw(self, renderer)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/collections.py", line 404, in draw
    mpath.Path(offsets), transOffset, tuple(facecolors[0]))
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_pdf.py", line 1934, in draw_markers
    marker, Op.use_xobject)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_pdf.py", line 732, in output
    self.write(fill([pdfRepr(x) for x in data]))
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_pdf.py", line 729, in write
    self.currentstream.write(data)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_pdf.py", line 524, in write
    self.file.write(compressed)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/instagraal", line 11, in <module>
    load_entry_point('instagraal', 'console_scripts', 'instagraal')()
  File "/src/instagraal/instagraal/instagraal.py", line 1178, in main
    output_folder=output_folder,
  File "/src/instagraal/instagraal/instagraal.py", line 160, in __init__
    output_folder=output_folder,
  File "/src/instagraal/instagraal/simu_single.py", line 74, in __init__
    self.select_data_set(name)
  File "/src/instagraal/instagraal/simu_single.py", line 743, in select_data_set
    thresh_factor=self.thresh_factor,
  File "/src/instagraal/instagraal/pyramid_sparse.py", line 113, in build_and_filter
    thresh_factor=thresh_factor,
  File "/src/instagraal/instagraal/pyramid_sparse.py", line 856, in remove_problematic_fragments
    plt.savefig("sparsity_plot.pdf")
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_pdf.py", line 2601, in print_pdf
    file.close()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_pdf.py", line 723, in close
    self.fh.close()
OSError: [Errno 28] No space left on device

Do you have any idea to solve this issue?
Best

**Comment by cmdoret** [comment]
Hello @gorliver 

Unfortunately, the instagraal container only works with docker (using nvidia-docker2) and not singularity.
However the specific error you got `No space left on device` should mean that your hard drive is full and the program crashes because cannot write its output files.
