### ISSUE TITLE
module.cpp:1:10: fatal error: boost/python.hpp: No such file or directory

### ISSUE THREAD

**Issue by papelypluma** [koszullab/instaGRAAL#31]
Hi instaGRAAL developers, I'd like to seek for help. I'm using the no_opengl branch of instaGRAAL following the previous issue that I had encountered. Now, instaGRAAL seems to work though the following error comes out after a short while. Does this have something to do with libboost? I checked that the system has libboost 1.71. Am not sure if this error occurs because of the Python headers that appear to be absent. Thanks a lot for your help!

> INFO :: kernels compiled
> INFO :: setup jumping distribution: start
> INFO :: Shape sub mat = (103382, 103382)
> INFO :: setup jumping distribution: done
> INFO :: recompiling for non-existent cache dir (/home/datb/.cache/codepy/codepy-compiler-cache-v5-py3.6.15.final.0/a94c4c01d73203ac29d06cb2931f5fda).
> /home/datb/.cache/codepy/codepy-compiler-cache-v5-py3.6.15.final.0/a94c4c01d73203ac29d06cb2931f5fda/module.cpp:1:10: fatal error: boost/python.hpp: No such file or directory
>     1 | #include <boost/python.hpp>
>       |          ^~~~~~~~~~~~~~~~~~
> compilation terminated.
> FAILED compiler invocation:x86_64-conda-linux-gnu-c++ -pthread -Wno-unused-result -Wsign-compare -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/datb/miniconda3/envs/instagraal/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/python_1638555655832/work=/usr/local/src/conda/python-3.6.15 -fdebug-prefix-map=/home/datb/miniconda3/envs/instagraal=/usr/local/src/conda-prefix -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/datb/miniconda3/include -c -DNDEBUG -I/home/datb/miniconda3/envs/instagraal/include/python3.6m -I/home/datb/tools/cuda_toolkit/include /home/datb/.cache/codepy/codepy-compiler-cache-v5-py3.6.15.final.0/a94c4c01d73203ac29d06cb2931f5fda/module.cpp -o /home/datb/.cache/codepy/codepy-compiler-cache-v5-py3.6.15.final.0/a94c4c01d73203ac29d06cb2931f5fda/module.o
> x86_64-conda-linux-gnu-c++ -pthread -Wno-unused-result -Wsign-compare -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/datb/miniconda3/envs/instagraal/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/python_1638555655832/work=/usr/local/src/conda/python-3.6.15 -fdebug-prefix-map=/home/datb/miniconda3/envs/instagraal=/usr/local/src/conda-prefix -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/datb/miniconda3/include -c -DNDEBUG -I/home/datb/miniconda3/envs/instagraal/include/python3.6m -I/home/datb/tools/cuda_toolkit/include /home/datb/.cache/codepy/codepy-compiler-cache-v5-py3.6.15.final.0/a94c4c01d73203ac29d06cb2931f5fda/module.cpp -o /home/datb/.cache/codepy/codepy-compiler-cache-v5-py3.6.15.final.0/a94c4c01d73203ac29d06cb2931f5fda/module.o
> Traceback (most recent call last):
>   File "/home/datb/miniconda3/envs/instagraal/bin/instagraal", line 33, in <module>
>     sys.exit(load_entry_point('instagraal==0.1.6', 'console_scripts', 'instagraal')())
>   File "/home/datb/miniconda3/envs/instagraal/lib/python3.6/site-packages/instagraal-0.1.6-py3.6.egg/instagraal/instagraal.py", line 1178, in main
>     output_folder=output_folder,
>   File "/home/datb/miniconda3/envs/instagraal/lib/python3.6/site-packages/instagraal-0.1.6-py3.6.egg/instagraal/instagraal.py", line 160, in __init__
>     output_folder=output_folder,
>   File "/home/datb/miniconda3/envs/instagraal/lib/python3.6/site-packages/instagraal-0.1.6-py3.6.egg/instagraal/simu_single.py", line 168, in __init__
>     self.pos,
>   File "/home/datb/miniconda3/envs/instagraal/lib/python3.6/site-packages/instagraal-0.1.6-py3.6.egg/instagraal/cuda_lib_gl_single.py", line 314, in __init__
>     self.setup_thrust_modules()
>   File "/home/datb/miniconda3/envs/instagraal/lib/python3.6/site-packages/instagraal-0.1.6-py3.6.egg/instagraal/cuda_lib_gl_single.py", line 802, in setup_thrust_modules
>     gcc_toolchain, nvcc_toolchain, debug=True
>   File "/home/datb/miniconda3/envs/instagraal/lib/python3.6/site-packages/codepy/cuda.py", line 83, in compile
>     object=True, **local_host_kwargs)
>   File "/home/datb/miniconda3/envs/instagraal/lib/python3.6/site-packages/codepy/jit.py", line 430, in compile_from_string
>     toolchain.build_object(ext_file, source_paths, debug=debug)
>   File "/home/datb/miniconda3/envs/instagraal/lib/python3.6/site-packages/codepy/toolchain.py", line 192, in build_object
>     raise CompileError("module compilation failed")
> codepy.CompileError: module compilation failed

**Comment by cmdoret** [comment]
HI @papelypluma,

If you have already installed the required headers, I suspect this could be linked to conda.
I am not too familiar with this, but I think there may be mismatches between the system compiler and conda include paths.

It may be better to do that compilation outside conda (conda deactivate).

**Comment by papelypluma** [comment]
Hi @cmdoret. Thanks for the hep and suggestion! Will try it out.

**Comment by nadegeguiglielmoni** [comment]
Hello,

Was your boost issue solved?
