### ISSUE TITLE
KeyError on import reference genome

### ISSUE THREAD

**Issue by anhong11** [koszullab/instaGRAAL#33]
Hi,

I try to use instaGRAAL to do Hi-C scaffolding with the output of hicstuff. Here is the error I got: 
```
INFO :: Start filling the pyramid
INFO :: pyramid built.
INFO :: init pyramid
INFO :: pyramid loaded
INFO :: loading data from level = 4
INFO :: import reference genome
Traceback (most recent call last):
  File "/usr/local/bin/instagraal", line 11, in <module>
    load_entry_point('instagraal', 'console_scripts', 'instagraal')()
  File "/src/instagraal/instagraal/instagraal.py", line 1178, in main
    output_folder=output_folder,
  File "/src/instagraal/instagraal/instagraal.py", line 160, in __init__
    output_folder=output_folder,
  File "/src/instagraal/instagraal/simu_single.py", line 106, in __init__
    self.level.build_seq_per_bin(genome_fasta=self.fasta)
  File "/src/instagraal/instagraal/pyramid_sparse.py", line 2215, in build_seq_per_bin
    seq_frag = self.pyramid.dict_sequence_contigs[init_contig][
KeyError: 'tig00000725|arrow|arrow_np1212'
```

The tig00000725|arrow|arrow_np1212 contig looks like:
```
>tig00000725|arrow|arrow_np1212 6077
caggttttcatgtaccaatcatggaatcttcgcgtcatcgttgttagagatctttcatctttgacgagaggcttcccgtaatggtatttgtgttcatccacctccaagaaatcataatgtacatcgtcaggcaggtaatctccaagattggtattgggcaaaatctccggatgattagcgacgatatcgctagacaccttgagcggggggcacgattggttcgcttgttcgcccagctgggcaattttttccccagcttgttgttctgctaacctttgatcactgatagtacttcccgaccgctccgct.....
```

**Comment by nadegeguiglielmoni** [comment]
Hello,

This is likely due to the character "|" in the contig names, biopython sometimes shortens the names. The easiest is to modify the contig names  in your fasta file to match the ones in the hicstuff output.

**Comment by anhong11** [comment]
Thanks for your quick response. I changed the contig name from ">tig00000725|arrow|arrow_np1212 6077" to ">tig00000725 6077", failed. Then change it from ">tig00000725 6077" to ">tig00000725", succeed. It is still running. Hopefully, I can get the results this time.

**Comment by nadegeguiglielmoni** [comment]
Good then, hope that you will be happy the result.
